envs: [api_key, grpc_address, grpc_port, db_user, db_pass]
api:
  url: http://146.0.36.96:1117/api/v1
  key:
  grpc_address:
  grpc_port:
  external_logger: http://146.0.36.96:7491/log
  image_processing: http://146.0.36.96:11111
database:
  name: tracking
  user:
  password:
  address: 146.0.36.96
  port: 5432
  schema: schema.sql
